name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app

jobs:
  build-package:
    runs-on: macOS-13

    steps:
      - uses: actions/checkout@main
      - name: Test
        run: set -o pipefail && make test-package | xcpretty

  build-ui-preview:
    runs-on: macOS-13

    steps:
      - uses: actions/checkout@main
      - name: Build
        run: set -o pipefail && make build-ui-preview | xcpretty

  test-ui-preview:
    runs-on: macOS-13

    steps:
      - uses: actions/checkout@main
      - name: Build
        run: set -o pipefail && make test-ui-preview | xcpretty
