name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_16_beta_6.app

jobs:
  build-package:
    runs-on: macOS-14

    steps:
      - uses: actions/checkout@main
      - name: Test
        run: set -o pipefail && make test-package | xcpretty

  build-ui-preview:
    runs-on: macOS-14

    steps:
      - uses: actions/checkout@main
      - name: Build
        run: set -o pipefail && make build-ui-preview | xcpretty

  test-ui-preview:
    runs-on: macOS-14

    steps:
      - uses: actions/checkout@main
      - name: UI test
        run: set -o pipefail && make test-ui-preview | xcpretty

      - name: Archive xcresult
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: xcresult-uitest
          path: /tmp/*.xcresult
          if-no-files-found: error

