name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app

jobs:
  build-package:
    runs-on: macOS-13

    steps:
      - uses: actions/checkout@main
      - name: Test
        run: cd app/xcode && swift test

  build-ui-preview:
    runs-on: macOS-13

    steps:
      - uses: actions/checkout@main
      - name: Build
        run: cd app/xcode/App && xcodebuild -project VCam.xcodeproj -scheme VCamUIPreview -derivedDataPath /tmp/build clean build
